spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
