spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout:
  data:
    redis:
      connect-timeout: ${SPRING_DATA_REDIS_CONNECT:2s}
      host: ${SPRING_DATA_REDIS_CONNECT:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:1s}

