services:
  accounts:
    image: "kathesama/account-service:s4"
    container_name: accounts-ms
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kathesamanet
  cards:
    image: "kathesama/card-service:s4"
    container_name: cards-ms
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kathesamanet
  loans:
    image: "kathesama/loan-service:s4"
    container_name: loans-ms
    ports:
      - "8002:8002"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kathesamanet
networks:
  kathesamanet:
    driver: "bridge"