build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Katherine Aguirre - QA Leader"
    email: "kathesama@gmail.com"
  onCallSupport:
    - (000) 555-1234
    - (000) 555-5678