server:
  port: 8002

spring:
  application:
    name: loan-service
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loan related local APIs "
  contactDetails:
    name: "Katherine Aguirre - Developer"
    email: "kathesama@gmail.com"
  onCallSupport:
    - (000) 555-1234
    - (000) 555-5678

#For PostgreSQL
#  datasource:
#    url: ${DB_HOST}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

#For MYSQL
#  datasource:
#    url: ${DB_HOST}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug