server:
  port: 8072

spring:
  datasource:
    autoconfigure: exclude
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
#          lower-case-service-id: true
#      routes:
#        - id: account-service
#          uri: lb://account-service
#          order: 8000
#          predicates:
#            - Path=/accounts/api/v1/**
#            - Path=/customers/api/v1/**
#        - id: card-service
#          uri: lb://card-service
#          order: 8001
#          predicates:
#            - Path=/cards/api/v1/**
#        - id: loan-service
#          uri: lb://loan-service
#          order: 8002
#          predicates:
#            - Path=/loans/api/v1/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:${default_service_url}}

default_service_url: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gateway-server
    version: v1

logging:
  level:
    com.kathesama.app.master.microservices.infrastructure.server.gateway: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
