server:
  port: 8001

info:
  app:
    name: card-service
    version: v1

logging:
  level:
    org.hibernate.SQL: debug
    com.kathesama.app.master.microservices.service.card: DEBUG
spring:
  application:
    name: card-service
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: "dev"
  config:
    import: optional:configserver:http://localhost:8888

  # For MYSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update



eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:${default_service_url}}

default_service_url: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
