server:
  port: 8001

logging:
  level:
    org.hibernate.SQL: debug

spring:
  application:
    name: card-service
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: "dev"
  config:
    import: optional:configserver:http://localhost:8071

  # For MYSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#  # datasource For H2 DB
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#For PostgreSQL
#  datasource:
#    url: ${DB_HOST}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

